temp/objects/Trailhead_Badge__c.object
<CustomObject>
    <description>A record of a badge attempt taken by a contact</description>
    <fields>
        <fullName>Contact__c</fullName>
        <description>The person who attempted or passed this badge</description>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Contacts selected must have &quot;Monitor Trailhead Badges&quot; = TRUE</errorMessage>
            <filterItems>
                <field>Contact.Monitor_Trailhead_Badges__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Trailhead Badge Attempts</relationshipLabel>
        <relationshipName>Trailhead_Badge_Attempts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Trailhead Badge Attempt</label>
    <nameField>
        <displayFormat>TBN-{00000000}</displayFormat>
        <label>Trailhead Badge Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trailhead Badge Attempts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/FutureClass.cls
global with sharing class FutureClass {
    
    @Future   
    public static void DeleteBadgesFuture(List<ID> IDsToDelete){
        integer badges = IDsToDelete.size();
        list<Trailhead_Badge__c> RecordsToDelete = [Select ID from Trailhead_Badge__c where Contact__c in :IDsToDelete];

        try {
            Delete RecordsToDelete;
            system.Debug(Badges + ' badge attempt records deleted');
        } catch(DmlException e) {
            System.debug('The following exception has occurred while trying to delete badge attempt records: ' + e.getMessage());
        }
    }
    
}